### ISSUE TITLE
Dear author,when I  Run "python camull_cli.py",I can't find this fold

### ISSUE THREAD

**Issue by McSpooder** [McSpooder/camull-net#9]
Dear author,when I  Run "python camull_cli.py",I can't find this fold

  conn = sqlite3.connect("..\\weights\\neural-network.db")
sqlite3.OperationalError: unable to open database file

can you help me?

_Originally posted by @yujianzhong3257298 in https://github.com/McSpooder/camull-net/issues/8#issuecomment-1106011606_

**Comment by McSpooder** [comment]
Heres a quick fix: https://fastupload.io/VRlBd3qbUkWH293. Just download it and put it in the repository.  I'm currently in the works of developing a more logical solution.

**Comment by McSpooder** [comment]
Okay I have since added a conditional for the file which solves the problem for me. Please let me know if it works so that I can close the issue.

**Comment by yujianzhong3257298** [comment]
Good job,my bro.hhhhhhhh
You safed me,best of luck.

**Comment by lincong8722** [comment]
> 这是一个快速修复：https://fastupload.io/VRlBd3qbUkWH293。只需下载并放入存储库即可。我目前正在开发一个更合理的解决方案。

Hi, @McSpooder 
This link is broken, could you please send it again? I would be grateful
